swagger: '2.0'
info:
  description: API Restful
  version: 1.0.0
  title: api_restful
basePath: /
tags:
  - name: api_restful
    description: API Restful
    externalDocs:
      description: Find out more
      url: http://swagger.io
schemes:
  - https
  - http
paths:
  /vendedor:
    post:
      tags:
        - vendedor
      summary: Salvar dados vendedor
      description: Salvar dados vendedor
      operationId: salvar
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
        - in: body
          name: salvar
          description: Criar dados Vendedor
          schema:
            $ref: '#/definitions/SalvarVendedor'
      responses:
        '201':
          description: Success
          schema:
            $ref: '#/definitions/SalvarVendedor'
    get:
      tags:
        - vendedor
      summary: vendedor
      description: ''
      operationId: getVendedor
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
              $ref: '#/definitions/Vendedor'
        '204':
          description: Not Found
  /atuacao:
    post:
      tags:
        - Atuacao
      summary: salvar atuacao
      description: salvar atuacao
      operationId: Atuacao
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
        - in: body
          name: save
          description: Salvar atuacao
          schema:
            $ref: '#/definitions/Atuacao'
      responses:
        '201':
          description: Success
          schema:
            $ref: '#/definitions/Atuacao'
  /vendedor/{id}:
    get:
      tags:
        - vendedor
      summary: vendedor id
      description: ''
      operationId: getVendedorId
      produces:
        - application/json
      parameters:
        - name: id
          in: path
          required: true
          format: int64
          type: integer
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/VendedorId'
        '204':
          description: Not Found
definitions:
  SalvarVendedor:
    type: object
    properties:
      nome:
        type: string
      telefone:
        type: string
      idade:
        type: string
      cidade:
        type: string
      estado:
        type: string
      regiao:
        type: string
  Atuacao:
    type: object
    properties:
      regiao:
        type: string
      estado:
        type: array
        items:
          $ref: '#/definitions/Estado'
  Estado:
    type: object
    properties:
      estados:
        type: string
  VendedorId:
    type: object
    properties:
      id:
        format: int64
        type: integer
      nome:
        type: string
      dataInclusao:
        type: string
      estado:
        type: array
        items:
          $ref: '#/definitions/Estado'
  Vendedor:
    type: object
    properties:
      nome:
        type: string
      'telefone:':
        type: string
      idade:
        type: string
      cidade:
        type: string
      estado:
        type: string
      estados:
        type: array
        items:
          $ref: '#/definitions/Estado'
